# Generated by Django 4.2.3 on 2023-07-25 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cartService", "0004_category_product_order_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="brand_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="category_pic",
            field=models.ImageField(blank=True, null=True, upload_to="category_pics/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_pic",
            field=models.ImageField(blank=True, null=True, upload_to="product_pics/"),
        ),
    ]
