# Generated by Django 4.2.3 on 2023-07-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cartService", "0005_alter_category_options_product_brand_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cartService.userprofile",
            ),
        ),
    ]
