# Generated by Django 4.2.3 on 2023-07-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cartService", "0007_alter_cart_cart_id_alter_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_id",
            new_name="order_tag",
        ),
    ]
