# Generated by Django 4.2.3 on 2023-08-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartService", "0011_alter_cart_total_price_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
    ]
